FROM alpine:latest

MAINTAINER tgadaria@cisco.com

ENV STREAM_COUNT "{{ stream_count }}"

RUN apk --update add openjdk8
RUN apk --update add curl
RUN apk --update add tar
RUN apk --update add bash

RUN mkdir ~/Downloads
RUN curl "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz" -o ~/Downloads/kafka.tgz
RUN mkdir ~/kafka
RUN tar -xvzf ~/Downloads/kafka.tgz --strip 1 -C ~/kafka/

COPY producer.properties consumer.properties start_mirror.sh /root/kafka/bin/

WORKDIR /root/kafka/bin/
RUN chmod +x start_mirror.sh

CMD ["sh","start_mirror.sh"]
