---

- name: Build Docker Image
  hosts: kafka-nodes
  user: "{{ kafka_user }}"
  gather_facts: yes
  become: yes
  roles:
    - { role: build_docker_image, state: "present", when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"}
