---

- name: zookeeper installation
  hosts: zookeeper-nodes
  user: "{{ zookeeper_user }}"
  gather_facts: yes
  become: yes
  roles:
    - { role: install_zookeeper, state: "present", when: "ansible_os_family== 'RedHat' and ansible_distribution_major_version == '7'"}

- name: kafka installation
  hosts: kafka-nodes
  user: "{{ kafka_user }}"
  gather_facts: yes
  become: yes
  roles:
    - { role: install_kafka, state: "present", when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"}
