---

- name: Create Base Directories for Zookeeper
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ zookeeper_tarball_dir }}"
    - "{{ zookeeper_conf_dir }}"
    - "{{ zookeeper_data_dir }}"

- name: Change ownership for Zookeeper Data Directory
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"


- name: Download Zookeeper Archive
  get_url:
    url: https://www-eu.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: "{{ zookeeper_tarball_dir }}"


- name: Unpack ZooKeeper
  unarchive:
    src: /home/{{ zookeeper_user }}/Downloads/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    extra_opts: ['--strip-components=1']
    dest: "{{ zookeeper_conf_dir }}"
    remote_src: yes


